### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '%'

### ISSUE THREAD

**Issue by iamywang** [compsec-snu/tiktag#1]
Hello, I am working on reproducing the experiment in Chromium 125. So far, I have successfully built the target APK. However, I encountered some issues with the JavaScript code.

The Chrome console throws the following error:  
**Uncaught SyntaxError: Unexpected token '%'**

![fig](https://github.com/user-attachments/assets/cce77651-c88b-486e-9f49-7e13adde0811)

Upon inspecting the source code, I noticed that several functions appear to be unimplemented in `tiktag.js`:
- Line 115,`%FlushAddress(probeArray, index);`
- Line 198, `const victim = BigInt(%GetDataPtr(myArray));`
- Linre 199, `const tmpAddr = BigInt(%GetDataPtr(tmpArray));`
- Line 200, `const access = BigInt(%GetDataPtr(accessArray));`
- Line 201, `const victim_arr = %GetValue(myArray, 1234);`
- Line 209, `%PrepareFunctionForOptimization(spectre_tag);`
- Line 215, `%OptimizeFunctionOnNextCall(spectre_tag);`
- Line 221, `while (%FlushLength(myArray) != 1) {`

I would greatly appreciate it if you could provide any guidance on resolving this issue.

**Comment by pkuGenuine** [comment]
The `%` prefix is used to call [v8 built-in functions](https://v8.dev/docs/builtin-functions). In Chrome, you can enable this feature with `--js-flags="--allow-natives-syntax"`.

However, `GetDataPtr` is not defined. I suppose that the author missed a patch file for v8.

**Comment by juppytt** [comment]
Sorry for the late response. I wasn't aware of this issue.
As @pkuGenuine mentioned, I omitted the V8 patch with GetDataPtr, but now it's available. To reproduce the libvpx vulnerability, the libvpx should also be reverted.
